name: test_app

sdkPath: .fvm/flutter_sdk

packages:
  - .
  - lib/packages/**

command:
  clean:
    hooks:
      post: melos exec --flutter -- "fvm flutter clean"
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: false

scripts:
  bootstrap:main:
    run: fvm flutter pub get
  bootstrap:package_1:
    run: cd lib/packages/package_1 && fvm flutter pub get
  bootstrap:package_2:
    run: cd lib/packages/package_2 && fvm flutter pub get
  bootstrap:package_3:
    run: cd lib/packages/package_3 && fvm flutter pub get
  bootstrap:all:
    run: melos run bootstrap:main && melos run bootstrap:package_1 && melos run bootstrap:package_2 && melos run bootstrap:package_3